version: "3"
services:
 tomcat1:
  image: 192.168.0.84:80/smapp/smappimage:latest
  container_name: smapp
  hostname: tomcat1
 tomcat2:
  image: 192.168.0.84:80/pepapp/pepappimage:latest
  container_name: pepapp
  hostname: tomcat2
 tomcat3:
  image: 192.168.0.84:80/portalapp/portalappimage:latest
  container_name: portalapp
  hostname: tomcat3
 httpd:
  container_name: httpd
  hostname: httpd
  image: 192.168.0.84:80/httpd/httpdimage
  ports:
  - "80:80"
